spring:
  datasource:
    url: jdbc:postgresql://db:5432/users
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: your_jwt_secret
  expiration: 3600
server:
  port: 8080 